  - name: Build iOS and auto-submit to TestFlight
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          APPLE_APPSTORE_ISSUER_ID: ${{ secrets.APPLE_APPSTORE_ISSUER_ID }}
          APPLE_APPSTORE_KEY_ID: ${{ secrets.APPLE_APPSTORE_KEY_ID }}
        run: |
          eas --version
          eas build -p ios --profile production --auto-submit --non-interactive
