name: EAS iOS Build & Submit (TestFlight)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js (Expo SDK 53 compatible)
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Install dependencies
        run: npm install

      - name: Sanity check Expo config
        run: npx expo config --json

      - name: Show versions
        run: |
          node -v
          npm -v
          eas --version

      - name: Build iOS & auto-submit to TestFlight
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: |
          eas build -p ios --profile production --non-interactive --auto-submit
